run-server:
	./gradlew server:run

run-coroutine-server:
	./gradlew coroutine-server:run

run-client:
	./gradlew client:run

run-coroutine-client:
	./gradlew coroutine-client:run

run-micronaut-server:
	./gradlew micronaut-grpc:run

.PHONY: \
	run-server \
	run-coroutine-server \
	run-client \
	run-coroutine-client \
	run-micronaut-server
