/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fortune;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-10-15")
public class FortuneTeller {

  public interface Iface {

    public FortuneResponse GetFortune(FortuneRequest fortune_request) throws UnfortunateException, org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void GetFortune(FortuneRequest fortune_request, org.apache.thrift.async.AsyncMethodCallback<FortuneResponse> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public FortuneResponse GetFortune(FortuneRequest fortune_request) throws UnfortunateException, org.apache.thrift.TException
    {
      send_GetFortune(fortune_request);
      return recv_GetFortune();
    }

    public void send_GetFortune(FortuneRequest fortune_request) throws org.apache.thrift.TException
    {
      GetFortune_args args = new GetFortune_args();
      args.setFortune_request(fortune_request);
      sendBase("GetFortune", args);
    }

    public FortuneResponse recv_GetFortune() throws UnfortunateException, org.apache.thrift.TException
    {
      GetFortune_result result = new GetFortune_result();
      receiveBase(result, "GetFortune");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.unfortunate != null) {
        throw result.unfortunate;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "GetFortune failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void GetFortune(FortuneRequest fortune_request, org.apache.thrift.async.AsyncMethodCallback<FortuneResponse> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      GetFortune_call method_call = new GetFortune_call(fortune_request, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class GetFortune_call extends org.apache.thrift.async.TAsyncMethodCall<FortuneResponse> {
      private FortuneRequest fortune_request;
      public GetFortune_call(FortuneRequest fortune_request, org.apache.thrift.async.AsyncMethodCallback<FortuneResponse> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.fortune_request = fortune_request;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("GetFortune", org.apache.thrift.protocol.TMessageType.CALL, 0));
        GetFortune_args args = new GetFortune_args();
        args.setFortune_request(fortune_request);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public FortuneResponse getResult() throws UnfortunateException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_GetFortune();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("GetFortune", new GetFortune());
      return processMap;
    }

    public static class GetFortune<I extends Iface> extends org.apache.thrift.ProcessFunction<I, GetFortune_args> {
      public GetFortune() {
        super("GetFortune");
      }

      public GetFortune_args getEmptyArgsInstance() {
        return new GetFortune_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      public GetFortune_result getResult(I iface, GetFortune_args args) throws org.apache.thrift.TException {
        GetFortune_result result = new GetFortune_result();
        try {
          result.success = iface.GetFortune(args.fortune_request);
        } catch (UnfortunateException unfortunate) {
          result.unfortunate = unfortunate;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("GetFortune", new GetFortune());
      return processMap;
    }

    public static class GetFortune<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, GetFortune_args, FortuneResponse> {
      public GetFortune() {
        super("GetFortune");
      }

      public GetFortune_args getEmptyArgsInstance() {
        return new GetFortune_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<FortuneResponse> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<FortuneResponse>() { 
          public void onComplete(FortuneResponse o) {
            GetFortune_result result = new GetFortune_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            GetFortune_result result = new GetFortune_result();
            if (e instanceof UnfortunateException) {
              result.unfortunate = (UnfortunateException) e;
              result.setUnfortunateIsSet(true);
              msg = result;
            } else if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, GetFortune_args args, org.apache.thrift.async.AsyncMethodCallback<FortuneResponse> resultHandler) throws org.apache.thrift.TException {
        iface.GetFortune(args.fortune_request,resultHandler);
      }
    }

  }

  public static class GetFortune_args implements org.apache.thrift.TBase<GetFortune_args, GetFortune_args._Fields>, java.io.Serializable, Cloneable, Comparable<GetFortune_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetFortune_args");

    private static final org.apache.thrift.protocol.TField FORTUNE_REQUEST_FIELD_DESC = new org.apache.thrift.protocol.TField("fortune_request", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new GetFortune_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new GetFortune_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable FortuneRequest fortune_request; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      FORTUNE_REQUEST((short)1, "fortune_request");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // FORTUNE_REQUEST
            return FORTUNE_REQUEST;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.FORTUNE_REQUEST, new org.apache.thrift.meta_data.FieldMetaData("fortune_request", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT          , "FortuneRequest")));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetFortune_args.class, metaDataMap);
    }

    public GetFortune_args() {
    }

    public GetFortune_args(
      FortuneRequest fortune_request)
    {
      this();
      this.fortune_request = fortune_request;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public GetFortune_args(GetFortune_args other) {
      if (other.isSetFortune_request()) {
        this.fortune_request = new FortuneRequest(other.fortune_request);
      }
    }

    public GetFortune_args deepCopy() {
      return new GetFortune_args(this);
    }

    @Override
    public void clear() {
      this.fortune_request = null;
    }

    @org.apache.thrift.annotation.Nullable
    public FortuneRequest getFortune_request() {
      return this.fortune_request;
    }

    public GetFortune_args setFortune_request(@org.apache.thrift.annotation.Nullable FortuneRequest fortune_request) {
      this.fortune_request = fortune_request;
      return this;
    }

    public void unsetFortune_request() {
      this.fortune_request = null;
    }

    /** Returns true if field fortune_request is set (has been assigned a value) and false otherwise */
    public boolean isSetFortune_request() {
      return this.fortune_request != null;
    }

    public void setFortune_requestIsSet(boolean value) {
      if (!value) {
        this.fortune_request = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case FORTUNE_REQUEST:
        if (value == null) {
          unsetFortune_request();
        } else {
          setFortune_request((FortuneRequest)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case FORTUNE_REQUEST:
        return getFortune_request();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case FORTUNE_REQUEST:
        return isSetFortune_request();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof GetFortune_args)
        return this.equals((GetFortune_args)that);
      return false;
    }

    public boolean equals(GetFortune_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_fortune_request = true && this.isSetFortune_request();
      boolean that_present_fortune_request = true && that.isSetFortune_request();
      if (this_present_fortune_request || that_present_fortune_request) {
        if (!(this_present_fortune_request && that_present_fortune_request))
          return false;
        if (!this.fortune_request.equals(that.fortune_request))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetFortune_request()) ? 131071 : 524287);
      if (isSetFortune_request())
        hashCode = hashCode * 8191 + fortune_request.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(GetFortune_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetFortune_request()).compareTo(other.isSetFortune_request());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetFortune_request()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fortune_request, other.fortune_request);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("GetFortune_args(");
      boolean first = true;

      sb.append("fortune_request:");
      if (this.fortune_request == null) {
        sb.append("null");
      } else {
        sb.append(this.fortune_request);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class GetFortune_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public GetFortune_argsStandardScheme getScheme() {
        return new GetFortune_argsStandardScheme();
      }
    }

    private static class GetFortune_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<GetFortune_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, GetFortune_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // FORTUNE_REQUEST
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.fortune_request = new FortuneRequest();
                struct.fortune_request.read(iprot);
                struct.setFortune_requestIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, GetFortune_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.fortune_request != null) {
          oprot.writeFieldBegin(FORTUNE_REQUEST_FIELD_DESC);
          struct.fortune_request.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class GetFortune_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public GetFortune_argsTupleScheme getScheme() {
        return new GetFortune_argsTupleScheme();
      }
    }

    private static class GetFortune_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<GetFortune_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, GetFortune_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetFortune_request()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetFortune_request()) {
          struct.fortune_request.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, GetFortune_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.fortune_request = new FortuneRequest();
          struct.fortune_request.read(iprot);
          struct.setFortune_requestIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class GetFortune_result implements org.apache.thrift.TBase<GetFortune_result, GetFortune_result._Fields>, java.io.Serializable, Cloneable, Comparable<GetFortune_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetFortune_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);
    private static final org.apache.thrift.protocol.TField UNFORTUNATE_FIELD_DESC = new org.apache.thrift.protocol.TField("unfortunate", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new GetFortune_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new GetFortune_resultTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable FortuneResponse success; // required
    public @org.apache.thrift.annotation.Nullable UnfortunateException unfortunate; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      UNFORTUNATE((short)1, "unfortunate");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // UNFORTUNATE
            return UNFORTUNATE;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT          , "FortuneResponse")));
      tmpMap.put(_Fields.UNFORTUNATE, new org.apache.thrift.meta_data.FieldMetaData("unfortunate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, UnfortunateException.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetFortune_result.class, metaDataMap);
    }

    public GetFortune_result() {
    }

    public GetFortune_result(
      FortuneResponse success,
      UnfortunateException unfortunate)
    {
      this();
      this.success = success;
      this.unfortunate = unfortunate;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public GetFortune_result(GetFortune_result other) {
      if (other.isSetSuccess()) {
        this.success = new FortuneResponse(other.success);
      }
      if (other.isSetUnfortunate()) {
        this.unfortunate = new UnfortunateException(other.unfortunate);
      }
    }

    public GetFortune_result deepCopy() {
      return new GetFortune_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
      this.unfortunate = null;
    }

    @org.apache.thrift.annotation.Nullable
    public FortuneResponse getSuccess() {
      return this.success;
    }

    public GetFortune_result setSuccess(@org.apache.thrift.annotation.Nullable FortuneResponse success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    @org.apache.thrift.annotation.Nullable
    public UnfortunateException getUnfortunate() {
      return this.unfortunate;
    }

    public GetFortune_result setUnfortunate(@org.apache.thrift.annotation.Nullable UnfortunateException unfortunate) {
      this.unfortunate = unfortunate;
      return this;
    }

    public void unsetUnfortunate() {
      this.unfortunate = null;
    }

    /** Returns true if field unfortunate is set (has been assigned a value) and false otherwise */
    public boolean isSetUnfortunate() {
      return this.unfortunate != null;
    }

    public void setUnfortunateIsSet(boolean value) {
      if (!value) {
        this.unfortunate = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((FortuneResponse)value);
        }
        break;

      case UNFORTUNATE:
        if (value == null) {
          unsetUnfortunate();
        } else {
          setUnfortunate((UnfortunateException)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case UNFORTUNATE:
        return getUnfortunate();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case UNFORTUNATE:
        return isSetUnfortunate();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof GetFortune_result)
        return this.equals((GetFortune_result)that);
      return false;
    }

    public boolean equals(GetFortune_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_unfortunate = true && this.isSetUnfortunate();
      boolean that_present_unfortunate = true && that.isSetUnfortunate();
      if (this_present_unfortunate || that_present_unfortunate) {
        if (!(this_present_unfortunate && that_present_unfortunate))
          return false;
        if (!this.unfortunate.equals(that.unfortunate))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      hashCode = hashCode * 8191 + ((isSetUnfortunate()) ? 131071 : 524287);
      if (isSetUnfortunate())
        hashCode = hashCode * 8191 + unfortunate.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(GetFortune_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetUnfortunate()).compareTo(other.isSetUnfortunate());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetUnfortunate()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.unfortunate, other.unfortunate);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("GetFortune_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("unfortunate:");
      if (this.unfortunate == null) {
        sb.append("null");
      } else {
        sb.append(this.unfortunate);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class GetFortune_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public GetFortune_resultStandardScheme getScheme() {
        return new GetFortune_resultStandardScheme();
      }
    }

    private static class GetFortune_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<GetFortune_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, GetFortune_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new FortuneResponse();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // UNFORTUNATE
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.unfortunate = new UnfortunateException();
                struct.unfortunate.read(iprot);
                struct.setUnfortunateIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, GetFortune_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.unfortunate != null) {
          oprot.writeFieldBegin(UNFORTUNATE_FIELD_DESC);
          struct.unfortunate.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class GetFortune_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public GetFortune_resultTupleScheme getScheme() {
        return new GetFortune_resultTupleScheme();
      }
    }

    private static class GetFortune_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<GetFortune_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, GetFortune_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetUnfortunate()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
        if (struct.isSetUnfortunate()) {
          struct.unfortunate.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, GetFortune_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.success = new FortuneResponse();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.unfortunate = new UnfortunateException();
          struct.unfortunate.read(iprot);
          struct.setUnfortunateIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
