/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fortune;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-10-15")
public enum Animal implements org.apache.thrift.TEnum {
  MONKEY(0),
  OWL(1),
  ANT(2),
  LIZARD(3),
  CAT(4);

  private final int value;

  private Animal(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Animal findByValue(int value) { 
    switch (value) {
      case 0:
        return MONKEY;
      case 1:
        return OWL;
      case 2:
        return ANT;
      case 3:
        return LIZARD;
      case 4:
        return CAT;
      default:
        return null;
    }
  }
}
